version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com

      # Retrieve SSH Key securely
      - echo "Retrieving SSH Key..."
      - aws ssm get-parameter --name "/app/ecsec2-key" --with-decryption --query "Parameter.Value" --output text > key.pem
      - chmod 400 key.pem

  build:
    commands:
      - echo Build started on `date`
      - echo Building JAR...
      - mvn clean package -DskipTests
      - echo Building Docker Image...
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
    - echo Pushing Image to ECR...
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/$IMAGE_REPO_NAME:latest
    - echo "Deploying to EC2 via SSH..."
    # SSH Command: Connects to EC2 -> Pulls new image -> Restarts container
    - ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$EC2_IP_ADDRESS "
      aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com && \
      docker pull $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/$IMAGE_REPO_NAME:latest && \
      docker stop ecsec2registry || true && \
      docker rm ecsec2registry || true && \
      docker run -d --name ecsec2registry -p 80:8080 \
      -e DB_URL=jdbc:mysql://$DB_ENDPOINT:3306/userdb?createDatabaseIfNotExist=true \
      -e DB_USERNAME=$DB_USER \
      -e DB_PASSWORD=$DB_PASS \
      $AWS_ACCOUNT_ID.dkr.ecr.ap-south-2.amazonaws.com/$IMAGE_REPO_NAME:latest
      "